// @ts-expect-error .open-next/worker.js is generated by the OpenNext build.
import nextWorker from "./.open-next/worker.js"

import { getDb } from "@nexus-vault/db"
import type { ResourceType } from "@nexus-vault/shared/resource-input"
import { processMetadataMessage } from "@/server/services/metadata-service"
import {
  processNotificationMessage,
  type NotificationQueueMessage,
} from "@/server/services/notification-service"
import type { MetadataQueueMessage } from "@/server/services/resource-service"

const METADATA_QUEUE_NAMES = new Set([
  "nexus-vault-metadata-local",
  "nexus-vault-metadata",
])
const NOTIFICATION_QUEUE_NAMES = new Set([
  "nexus-vault-notifications-local",
  "nexus-vault-notifications",
])

export default {
  ...nextWorker,
  async queue(batch: MessageBatch<unknown>, env: CloudflareEnv) {
    if (
      !METADATA_QUEUE_NAMES.has(batch.queue) &&
      !NOTIFICATION_QUEUE_NAMES.has(batch.queue)
    ) {
      await nextWorker.queue?.(batch, env)
      return
    }

    const db = getDb(env.DB)

    await Promise.all(
      batch.messages.map(async (message) => {
        const body =
          METADATA_QUEUE_NAMES.has(batch.queue)
            ? parseMetadataQueueMessage(message.body)
            : parseNotificationQueueMessage(message.body)
        if (!body) {
          message.ack()
          return
        }

        try {
          if (body.kind === "metadata.resolve") {
            await processMetadataMessage(db, body, { env })
          } else {
            await processNotificationMessage(db, body)
          }
          message.ack()
        } catch (error) {
          console.error("Queue message failed", {
            queue: batch.queue,
            messageId: message.id,
            error,
          })
          message.retry()
        }
      })
    )
  },
} satisfies ExportedHandler<CloudflareEnv>

function parseMetadataQueueMessage(body: unknown): MetadataQueueMessage | null {
  if (!body || typeof body !== "object") return null
  const candidate = body as Partial<MetadataQueueMessage>

  if (candidate.kind !== "metadata.resolve") return null
  if (typeof candidate.resourceId !== "string" || !candidate.resourceId) return null
  if (typeof candidate.vaultId !== "string" || !candidate.vaultId) return null
  if (!isResourceType(candidate.type)) return null
  if (candidate.dedupeKey !== undefined && typeof candidate.dedupeKey !== "string") return null
  if (typeof candidate.requestedAt !== "string" || !candidate.requestedAt) return null

  return {
    kind: "metadata.resolve",
    resourceId: candidate.resourceId,
    vaultId: candidate.vaultId,
    type: candidate.type,
    dedupeKey: candidate.dedupeKey,
    requestedAt: candidate.requestedAt,
  }
}

function parseNotificationQueueMessage(body: unknown): NotificationQueueMessage | null {
  if (!body || typeof body !== "object") return null
  const candidate = body as Partial<NotificationQueueMessage>

  if (candidate.kind !== "notification.create") return null
  if (candidate.userId !== undefined && typeof candidate.userId !== "string") return null
  if (candidate.userEmail !== undefined && typeof candidate.userEmail !== "string") return null
  if (!candidate.userId && !candidate.userEmail) return null
  if (candidate.vaultId !== undefined && typeof candidate.vaultId !== "string") return null
  if (typeof candidate.type !== "string" || !candidate.type) return null
  if (typeof candidate.title !== "string" || !candidate.title) return null
  if (candidate.body !== undefined && typeof candidate.body !== "string") return null
  if (typeof candidate.requestedAt !== "string" || !candidate.requestedAt) return null

  return {
    kind: "notification.create",
    userId: candidate.userId,
    userEmail: candidate.userEmail,
    vaultId: candidate.vaultId,
    type: candidate.type,
    title: candidate.title,
    body: candidate.body,
    requestedAt: candidate.requestedAt,
  }
}

function isResourceType(value: unknown): value is ResourceType {
  return (
    value === "magnet" ||
    value === "twitter" ||
    value === "baidu_pan" ||
    value === "pan_115" ||
    value === "pan_123" ||
    value === "quark_pan" ||
    value === "uc_pan" ||
    value === "xunlei_pan" ||
    value === "pikpak" ||
    value === "onedrive" ||
    value === "google_drive" ||
    value === "dropbox" ||
    value === "alist" ||
    value === "http" ||
    value === "youtube" ||
    value === "other"
  )
}
