import { Hono } from "hono";

import type { AppEnv } from "../../types/context";
import { registerLegacyRoute } from "./adapter";

import * as accountIntegrations from "./account/integrations/route";
import * as accountXCom from "./account/integrations/x-com/route";
import * as health from "./health/route";
import * as localMediaMultipart from "./local-media/multipart/route";
import * as localMediaMultipartSign from "./local-media/multipart/sign/route";
import * as media from "./media/[...key]/route";
import * as notifications from "./notifications/route";
import * as notificationSummary from "./notifications/summary/route";
import * as notificationRead from "./notifications/[notificationId]/read/route";
import * as readLaterList from "./resource-read-later/route";
import * as resourceStarsList from "./resource-stars/route";
import * as resource from "./resources/[resourceId]/route";
import * as resourceStash from "./resource-stash/route";
import * as resourceStashOrganize from "./resource-stash/resources/[resourceId]/organize/route";
import * as resourceAnnotation from "./resources/[resourceId]/annotation/route";
import * as resourceLocalMedia from "./resources/[resourceId]/local-media/route";
import * as resourceLocalMediaMultipart from "./resources/[resourceId]/local-media/multipart/route";
import * as resourceMediaDownload from "./resources/[resourceId]/media/[mediaIndex]/download/route";
import * as resourceMediaStream from "./resources/[resourceId]/media/[mediaIndex]/stream/route";
import * as resourceMetadataResolve from "./resources/[resourceId]/metadata/resolve/route";
import * as resourceMetadataStream from "./resources/[resourceId]/metadata/stream/route";
import * as resourceReadLater from "./resources/[resourceId]/read-later/route";
import * as resourceStar from "./resources/[resourceId]/star/route";
import * as resourceTransfer from "./resources/[resourceId]/transfer/route";
import * as resources from "./resources/route";
import * as resourceTransferTargets from "./resources/transfer-targets/route";
import * as resourcesTransfer from "./resources/transfer/route";
import * as workspaceSearch from "./search/route";
import * as shareSubmissions from "./shares/[slug]/submissions/route";
import * as shareDetail from "./shares/[slug]/route";
import * as shareUnlock from "./shares/[slug]/unlock/route";
import * as socialVideo from "./social-video/media/route";
import * as stars from "./stars/route";
import * as vault from "./vaults/[vaultId]/route";
import * as vaultAlerts from "./vaults/[vaultId]/alerts/route";
import * as vaultAlertsRead from "./vaults/[vaultId]/alerts/read/route";
import * as collaborators from "./vaults/[vaultId]/collaborators/route";
import * as collaborator from "./vaults/[vaultId]/collaborators/[collaboratorId]/route";
import * as vaultExport from "./vaults/[vaultId]/export/route";
import * as vaultFork from "./vaults/[vaultId]/fork/route";
import * as vaultResources from "./vaults/[vaultId]/resources/route";
import * as vaultLocalMedia from "./vaults/[vaultId]/resources/local-media/route";
import * as vaultLocalMediaMultipart from "./vaults/[vaultId]/resources/local-media/multipart/route";
import * as vaultMetadataStatus from "./vaults/[vaultId]/resources/metadata-status/route";
import * as vaultResourceReorder from "./vaults/[vaultId]/resources/reorder/route";
import * as vaultShare from "./vaults/[vaultId]/share/route";
import * as spaces from "./vaults/[vaultId]/spaces/route";
import * as space from "./vaults/[vaultId]/spaces/[spaceId]/route";
import * as spaceTransfer from "./vaults/[vaultId]/spaces/[spaceId]/transfer/route";
import * as spacesReorder from "./vaults/[vaultId]/spaces/reorder/route";
import * as vaultStar from "./vaults/[vaultId]/star/route";
import * as submissions from "./vaults/[vaultId]/submissions/route";
import * as submissionApprove from "./vaults/[vaultId]/submissions/[submissionId]/approve/route";
import * as submissionReject from "./vaults/[vaultId]/submissions/[submissionId]/reject/route";
import * as vaults from "./vaults/route";
import * as vaultImport from "./vaults/import/route";
import * as sharedVaults from "./vaults/shared/route";

export const apiV1 = new Hono<AppEnv>();

registerLegacyRoute(apiV1, "/health", health);
registerLegacyRoute(apiV1, "/account/integrations", accountIntegrations);
registerLegacyRoute(apiV1, "/account/integrations/x-com", accountXCom);
registerLegacyRoute(apiV1, "/local-media/multipart", localMediaMultipart);
registerLegacyRoute(apiV1, "/local-media/multipart/sign", localMediaMultipartSign);
registerLegacyRoute(apiV1, "/media/*", media, { wildcardParam: "key" });
registerLegacyRoute(apiV1, "/notifications", notifications);
registerLegacyRoute(apiV1, "/notifications/summary", notificationSummary);
registerLegacyRoute(apiV1, "/notifications/:notificationId/read", notificationRead);
registerLegacyRoute(apiV1, "/resource-read-later", readLaterList);
registerLegacyRoute(apiV1, "/resource-stars", resourceStarsList);
registerLegacyRoute(apiV1, "/resources", resources);
registerLegacyRoute(apiV1, "/resource-stash", resourceStash);
registerLegacyRoute(apiV1, "/resource-stash/resources/:resourceId/organize", resourceStashOrganize);
registerLegacyRoute(apiV1, "/resources/transfer", resourcesTransfer);
registerLegacyRoute(apiV1, "/search", workspaceSearch);
registerLegacyRoute(apiV1, "/resources/transfer-targets", resourceTransferTargets);
registerLegacyRoute(apiV1, "/resources/:resourceId", resource);
registerLegacyRoute(apiV1, "/resources/:resourceId/annotation", resourceAnnotation);
registerLegacyRoute(apiV1, "/resources/:resourceId/local-media", resourceLocalMedia);
registerLegacyRoute(apiV1, "/resources/:resourceId/local-media/multipart", resourceLocalMediaMultipart);
registerLegacyRoute(apiV1, "/resources/:resourceId/media/:mediaIndex/download", resourceMediaDownload);
registerLegacyRoute(apiV1, "/resources/:resourceId/media/:mediaIndex/stream", resourceMediaStream);
registerLegacyRoute(apiV1, "/resources/:resourceId/metadata/resolve", resourceMetadataResolve);
registerLegacyRoute(apiV1, "/resources/:resourceId/metadata/stream", resourceMetadataStream);
registerLegacyRoute(apiV1, "/resources/:resourceId/read-later", resourceReadLater);
registerLegacyRoute(apiV1, "/resources/:resourceId/star", resourceStar);
registerLegacyRoute(apiV1, "/resources/:resourceId/transfer", resourceTransfer);
registerLegacyRoute(apiV1, "/shares/:slug/submissions", shareSubmissions);
registerLegacyRoute(apiV1, "/shares/:slug/unlock", shareUnlock);
registerLegacyRoute(apiV1, "/shares/:slug", shareDetail);
registerLegacyRoute(apiV1, "/social-video/media", socialVideo);
registerLegacyRoute(apiV1, "/stars", stars);
registerLegacyRoute(apiV1, "/vaults", vaults);
registerLegacyRoute(apiV1, "/vaults/import", vaultImport);
registerLegacyRoute(apiV1, "/vaults/shared", sharedVaults);
registerLegacyRoute(apiV1, "/vaults/:vaultId", vault);
registerLegacyRoute(apiV1, "/vaults/:vaultId/alerts", vaultAlerts);
registerLegacyRoute(apiV1, "/vaults/:vaultId/alerts/read", vaultAlertsRead);
registerLegacyRoute(apiV1, "/vaults/:vaultId/collaborators", collaborators);
registerLegacyRoute(apiV1, "/vaults/:vaultId/collaborators/:collaboratorId", collaborator);
registerLegacyRoute(apiV1, "/vaults/:vaultId/export", vaultExport);
registerLegacyRoute(apiV1, "/vaults/:vaultId/fork", vaultFork);
registerLegacyRoute(apiV1, "/vaults/:vaultId/resources", vaultResources);
registerLegacyRoute(apiV1, "/vaults/:vaultId/resources/local-media", vaultLocalMedia);
registerLegacyRoute(apiV1, "/vaults/:vaultId/resources/local-media/multipart", vaultLocalMediaMultipart);
registerLegacyRoute(apiV1, "/vaults/:vaultId/resources/metadata-status", vaultMetadataStatus);
registerLegacyRoute(apiV1, "/vaults/:vaultId/resources/reorder", vaultResourceReorder);
registerLegacyRoute(apiV1, "/vaults/:vaultId/share", vaultShare);
registerLegacyRoute(apiV1, "/vaults/:vaultId/spaces", spaces);
// Keep the static reorder endpoint ahead of the dynamic :spaceId route.
registerLegacyRoute(apiV1, "/vaults/:vaultId/spaces/reorder", spacesReorder);
registerLegacyRoute(apiV1, "/vaults/:vaultId/spaces/:spaceId", space);
registerLegacyRoute(apiV1, "/vaults/:vaultId/spaces/:spaceId/transfer", spaceTransfer);
registerLegacyRoute(apiV1, "/vaults/:vaultId/star", vaultStar);
registerLegacyRoute(apiV1, "/vaults/:vaultId/submissions", submissions);
registerLegacyRoute(apiV1, "/vaults/:vaultId/submissions/:submissionId/approve", submissionApprove);
registerLegacyRoute(apiV1, "/vaults/:vaultId/submissions/:submissionId/reject", submissionReject);
