import { consumeQueueBatch } from "./server/queues/worker-consumer"
import type { QueueMessage } from "./server/queues/messages"

// Generated by `opennextjs-cloudflare build`.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated by OpenNext during the Cloudflare build.
import openNextWorker from "../.open-next/worker.js"

// Generated by `opennextjs-cloudflare build`.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated by OpenNext during the Cloudflare build.
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from "../.open-next/worker.js"

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)
    const requestMeta = {
      method: request.method,
      path: url.pathname,
      ray: request.headers.get("cf-ray") ?? undefined,
    }

    try {
      const response = await openNextWorker.fetch(request, env, ctx)

      if (response instanceof Response) return response

      console.error("Worker handler did not return a Response", {
        ...requestMeta,
        responseType: typeof response,
      })
      return new Response("Worker handler did not return a Response.", {
        status: 500,
      })
    } catch (error) {
      console.error("Worker request failed", {
        ...requestMeta,
        error:
          error instanceof Error
            ? { name: error.name, message: error.message, stack: error.stack }
            : error,
      })

      return new Response("Worker request failed.", { status: 500 })
    }
  },
  queue(batch, env) {
    return consumeQueueBatch(batch, env)
  },
} satisfies ExportedHandler<CloudflareEnv, QueueMessage>
